project:
  type: website
  output-dir: docs

website:
  title: "Ellen Bledsoe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

